/// Flutter icons FlutterIcon
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcon
///      fonts:
///       - asset: fonts/FlutterIcon.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class FlutterIcon {
  FlutterIcon._();

  static const _kFontFam = 'FlutterIcon';

  static const IconData cloud_moon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fahrenheit = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData clouds_flash_alt = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData sun_inv = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData moon_inv = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData clouds_inv = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData clouds_flash_inv = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData temperature = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData na = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData celcius = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cloud_sun_inv = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cloud_moon_inv = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData eclipse = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData mist = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData wind = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData snowflake = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData snow = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData snow_alt = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData cloud_inv = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData hail = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData clouds = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData clouds_flash = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData cloud_flash_inv = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData drizzle_inv = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData rain_inv = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData fog_sun = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData fog_moon = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData fog_cloud = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData fog = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData cloud_flash = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData cloud_flash_alt = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData drizzle = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData rain = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData windy = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData windy_rain_inv = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData snow_inv = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData snow_heavy_inv = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData windy_inv = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData sunrise = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData hail_inv = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData windy_rain = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData snow_heavy = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData cloud_sun = const IconData(0xe82e, fontFamily: _kFontFam);
}
